# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/COP/newsc/vivado/sccpu_project/sccpu_project.cache/wt [current_project]
set_property parent.project_path D:/COP/newsc/vivado/sccpu_project/sccpu_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/COP/newsc/vivado/sccpu_project/sccpu_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv D:/COP/newsc/source-sc/sccomp_top.sv
read_verilog -library xil_defaultlib {
  D:/COP/newsc/source-sc/ctrl_encode_def.v
  D:/COP/newsc/source-sc/EXT.v
  D:/COP/newsc/source-sc/NPC.v
  D:/COP/newsc/source-sc/PC.v
  D:/COP/newsc/source-sc/RF.v
  D:/COP/newsc/source-sc/SCCPU.v
  D:/COP/newsc/source-sc/alu.v
  D:/COP/newsc/source-sc/ctrl.v
  D:/COP/newsc/source-sc/dm.v
  D:/COP/newsc/source-sc/hex_to_7seg.v
  D:/COP/newsc/source-sc/im.v
  D:/COP/newsc/source-sc/scan_7seg.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/COP/newsc/constraints/Nexys4DDR.xdc
set_property used_in_implementation false [get_files D:/COP/newsc/constraints/Nexys4DDR.xdc]


synth_design -top sccomp_top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef sccomp_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file sccomp_top_utilization_synth.rpt -pb sccomp_top_utilization_synth.pb"
